apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: iosmcn-ran-cucp-gitrepo
  namespace: flux-system
spec:
  interval: 10s
  url: https://github.com/ios-mcn-ran/ios-mcn-ran
  ref:
    branch: kube-orchestration
  ignore: |
    # exclude all
    /*
    # include charts dir
    !/charts
