apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iosmcnran-du 
  namespace: iosmcnran
spec:
  interval: 1m
  chart:
    spec:
      chart: ./cicd/oai-5g-ran/oai-du
      version: '2.0.0'
      sourceRef:
        kind: GitRepository
        name:  iosmcn-ran-du-gitrepo
        namespace: flux-system
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: iosmcnran
  valuesFrom:
  - kind: ConfigMap
    name: iosmcn-ran-du-values
    valuesKey: values.yaml

